# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rake", "~> 13.1"

gem 'numo-linalg', '~> 0.1.7'

gem 'numo-narray', '~> 0.9.2'

gem 'numo-openblas', '~> 0.4.11'
